# Generated by Django 3.0.8 on 2020-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ชื่อ', models.CharField(max_length=200)),
                ('นามสกุล', models.CharField(max_length=200)),
                ('วันที่', models.CharField(max_length=200)),
                ('เวลา', models.CharField(max_length=200)),
            ],
        ),
    ]
